version: '3.8'

services:
  bot:
    build: .
    container_name: telegram_bot
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/telegram_bot_db
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: telegram_bot_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: telegram_bot_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
